# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: Basys3_Master.xdc

# IP: ip/ila_uart/ila_uart.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila_uart || ORIG_REF_NAME==ila_uart}]
